DROP TABLE TBL_CLIENTE
GO

CREATE TABLE [dbo].[TBL_CLIENTE](
	[DOC_CLIENTE] [varchar](10) NULL,
	[NOMBRE] [nchar](10) NULL,
	[DIRECCION] [nchar](10) NULL,
	[TELEFONO] [nchar](10) NULL
) ON [PRIMARY]

GO



DROP TABLE TBL_SERVICIO
GO

CREATE TABLE [dbo].[TBL_SERVICIO](
	[NUM_RESERVA] [nchar](10) NOT NULL ,
	[FECHA_INI] [nchar](10) NULL,
	[FECHA_FIN] [nchar](10) NULL,
	[PRECIO] [nchar](10) NULL,
	[COD_CLIENTE] [nchar](10) NULL
) ON [PRIMARY]

GO

DROP TABLE TBL_VEHICULO 
GO

CREATE TABLE [dbo].[TBL_VEHICULO](	
	[MATRICULA] [nchar](10) NULL,
	[MARCA] [nchar](100) NULL,
	[MODELO] INT NULL,
	[ESTADO] [nchar](10) NULL
) ON [PRIMARY]

GO



DROP TABLE TBL_MECANICO
GO

CREATE TABLE [dbo].[TBL_MECANICO](	
	[COD_MECANICO] [nchar](10) NULL,
	[MECANICO] [nchar](10) NULL
) ON [PRIMARY]

GO

DROP TABLE TBL_REPUESTOS
GO

CREATE TABLE [dbo].[TBL_REPUESTOS](
	[NUM_REPUESTO] [nchar](10) NULL ,
	[MATRICULA] [nchar](10) NULL,
	
) ON [PRIMARY]

GO


