DROP PROCEDURE SP_CLIENTE_CREAR
GO 

CREATE PROCEDURE SP_CLIENTE_CREAR
@DOC_CLIENTE VARCHAR(100),
@NOMBRE VARCHAR(20),
@DIRECCION VARCHAR(20) NULL,
@TELEFONO VARCHAR(20) NULL

AS
BEGIN

	INSERT INTO TBL_CLIENTE (DOC_CLIENTE, NOMBRE, DIRECCION,TELEFONO)
	VALUES (@DOC_CLIENTE, @NOMBRE, @DIRECCION,@TELEFONO)

	SELECT @@IDENTITY DOC_CLIENTE
END;

DROP PROCEDURE SP_VEHICULO_CREAR
GO

CREATE PROCEDURE SP_VEHICULO_CREAR
@MATRICULA VARCHAR(100),
@MARCA VARCHAR(20),
@MODELO INT NULL,
@ESTADO VARCHAR(200) NULL

AS
BEGIN

	INSERT INTO TBL_VEHICULO (MATRICULA, MARCA, MODELO,ESTADO)
	VALUES (@MATRICULA, @MARCA, @MODELO,@ESTADO)

	SELECT @@IDENTITY MATRICULA
END;

CREATE PROCEDURE SP_GENERAL_CONSULTAR
AS
SELECT P.MATRICULA
	 , P.MARCA
	 , P.MODELO
	 , P.ESTADO
 FROM TBL_VEHICULO P
 ORDER BY P.MATRICULA
 
 DROP PROCEDURE SP_VEHICULO_ELIMINAR
 GO 
 
 CREATE PROCEDURE SP_VEHICULO_ELIMINAR
@ID_MATRICULA VARCHAR(100)
AS
BEGIN
	
	DELETE TBL_VEHICULO 	
	--WHERE MATRICULA = @ID_MATRICULA
END