<?xml version="1.0" encoding="utf-8"?><Database Name="Pru_Omar_Chacon" Class="dbQDDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESARROLLO1;Initial Catalog=Pru_Omar_Chacon;Integrated Security=True" SettingsObjectName="DataAccess.Properties.Settings" SettingsPropertyName="Pru_Omar_ChaconConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.SP_CLIENTE_CREAR" Method="SP_CLIENTE_CREAR">
    <Parameter Name="DOC_CLIENTE" Parameter="dOC_CLIENTE" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NOMBRE" Parameter="nOMBRE" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="DIRECCION" Parameter="dIRECCION" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="TELEFONO" Parameter="tELEFONO" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="SP_CLIENTE_CREARResult">
      <Column Name="DOC_CLIENTE" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_VEHICULO_CREAR" Method="SP_VEHICULO_CREAR">
    <Parameter Name="MATRICULA" Parameter="mATRICULA" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="MARCA" Parameter="mARCA" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="MODELO" Parameter="mODELO" Type="System.Int32" DbType="Int" />
    <Parameter Name="ESTADO" Parameter="eSTADO" Type="System.String" DbType="VarChar(200)" />
    <ElementType Name="SP_VEHICULO_CREARResult">
      <Column Name="MATRICULA" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_GENERAL_CONSULTAR" Method="SP_GENERAL_CONSULTAR">
    <ElementType Name="SP_GENERAL_CONSULTARResult">
      <Column Name="MATRICULA" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MARCA" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="MODELO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ESTADO" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_VEHICULO_ELIMINAR" Method="SP_VEHICULO_ELIMINAR">
    <Parameter Name="ID_MATRICULA" Parameter="iD_MATRICULA" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
</Database>