#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Pru_Omar_Chacon")]
	public partial class dbQDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public dbQDDataContext() : 
				base(global::DataAccess.Properties.Settings.Default.Pru_Omar_ChaconConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbQDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CLIENTE_CREAR")]
		public ISingleResult<SP_CLIENTE_CREARResult> SP_CLIENTE_CREAR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOC_CLIENTE", DbType="VarChar(100)")] string dOC_CLIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="VarChar(20)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIRECCION", DbType="VarChar(20)")] string dIRECCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TELEFONO", DbType="VarChar(20)")] string tELEFONO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dOC_CLIENTE, nOMBRE, dIRECCION, tELEFONO);
			return ((ISingleResult<SP_CLIENTE_CREARResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_VEHICULO_CREAR")]
		public ISingleResult<SP_VEHICULO_CREARResult> SP_VEHICULO_CREAR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MATRICULA", DbType="VarChar(100)")] string mATRICULA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MARCA", DbType="VarChar(20)")] string mARCA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MODELO", DbType="Int")] System.Nullable<int> mODELO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ESTADO", DbType="VarChar(200)")] string eSTADO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mATRICULA, mARCA, mODELO, eSTADO);
			return ((ISingleResult<SP_VEHICULO_CREARResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_GENERAL_CONSULTAR")]
		public ISingleResult<SP_GENERAL_CONSULTARResult> SP_GENERAL_CONSULTAR()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_GENERAL_CONSULTARResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_VEHICULO_ELIMINAR")]
		public int SP_VEHICULO_ELIMINAR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_MATRICULA", DbType="VarChar(100)")] string iD_MATRICULA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_MATRICULA);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class SP_CLIENTE_CREARResult
	{
		
		private System.Nullable<decimal> _DOC_CLIENTE;
		
		public SP_CLIENTE_CREARResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOC_CLIENTE", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> DOC_CLIENTE
		{
			get
			{
				return this._DOC_CLIENTE;
			}
			set
			{
				if ((this._DOC_CLIENTE != value))
				{
					this._DOC_CLIENTE = value;
				}
			}
		}
	}
	
	public partial class SP_VEHICULO_CREARResult
	{
		
		private System.Nullable<decimal> _MATRICULA;
		
		public SP_VEHICULO_CREARResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATRICULA", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MATRICULA
		{
			get
			{
				return this._MATRICULA;
			}
			set
			{
				if ((this._MATRICULA != value))
				{
					this._MATRICULA = value;
				}
			}
		}
	}
	
	public partial class SP_GENERAL_CONSULTARResult
	{
		
		private string _MATRICULA;
		
		private string _MARCA;
		
		private System.Nullable<int> _MODELO;
		
		private string _ESTADO;
		
		public SP_GENERAL_CONSULTARResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATRICULA", DbType="NChar(10)")]
		public string MATRICULA
		{
			get
			{
				return this._MATRICULA;
			}
			set
			{
				if ((this._MATRICULA != value))
				{
					this._MATRICULA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARCA", DbType="NChar(100)")]
		public string MARCA
		{
			get
			{
				return this._MARCA;
			}
			set
			{
				if ((this._MARCA != value))
				{
					this._MARCA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODELO", DbType="Int")]
		public System.Nullable<int> MODELO
		{
			get
			{
				return this._MODELO;
			}
			set
			{
				if ((this._MODELO != value))
				{
					this._MODELO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="NChar(10)")]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
